language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: nZpMhFrPWItMSCnxemTATJS9MQOh3qJ5EVT06HAHAEaVxbLAqnpkJrYHppPnW8KhrSqpBpYm4rtQXTs20oLsYB/A1R1gHgAvojoIijhAAnur8xuC/huY3TOmwTVTT7RViC1PJNVAqt9eWJbR6SIVxtusPGzozJWdtdkTISDv4CSbosKAT5dlWHs0AMgvIwCXbnsu8p+tk/ovrM9NODKVuyox+PT5uajtsX9hokdeP6SoD/Px5lsSEioV/leQuVLMO9ioX+IvUBIbOeFW6de6ikVv68QU8x7Y5EGvUpo/wJoYzlwCd48B+GEcCALqizGqZS2LkDzGbuIyK/hLhb1sJj4rW8TYCKA/r4oxIdSO5oEBGNJ61plJY7763RDsBXPWMXKpSmHZoBfVS/LUtdvaynweAVewvM/bFai7pHTPSXZRqO0sFSHOzcCpuTX7KDxIfUmA0kTFRE8S67Yyu17GQARDmUlo1YTZxiPeIK+zqN9TSVltEyxCSjstouhF34zOs4oYgTt6H9abfl4AColMw8taYFMj8tIcAwoPV0ZilI6lSpuDujWp4bcS0NPI4W2iVXpYceCJEUoluFBeOnh99YwXE9Pq3gAMb7KtV7bo4nywBpOxgoo5pcRyAl/AD69KE3sTt8bbpdbq3/4vJjwZkcgybPYebdVrlLzoOlyQ/IY=
  app: resistance-pwa
  on:
    repo: balegas/resistance-pwa
